name: Update README.md
run-name: ${{ github.event.workflow_run.head_commit.message }}
on:
  push:
jobs:
  Refresh_README-md:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch dashboard
        run: |
          echo '[![solved.ac Profile](http://mazassumnida.wtf/api/generate_badge?boj=seyu)](https://solved.ac/seyu)' > README.md
          curl https://solved.ac/api/v3/user/top_100?handle=seyu \
              | jq '.items[] | .level' \
              | sed 's/^/<img width="16px" height="16px" src="https:\/\/static.solved.ac\/tier_small\//' \
              | sed 's/$/.svg" \/>/' \
              >> README.md
