name: Update README.md
run-name: ${{ github.event.workflow_run.head_commit.message }}
on:
  push:
    paths:
      - "백준/**"
jobs:
  refresh_badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rebuild README.md
        run: |
          python3 .github/readme_script.py seyu > README.md
      - name: Commit and Push README.md
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -am "Update README.md"
          git push
