name: Refresh README.md
run-name: ${{ github.event.workflow_run.head_commit.message }}
on:
  push:
    paths:
      - "백준/**"
jobs:
  refresh:
    runs-on: ubuntu-latest
    name: Refresh README.md
    steps:
      - uses: actions/checkout@v4
      - uses: seheon99/baekjoon-summary@84d86b3137f6b45e52dcb1d60528ef28bbde411f
        with:
          username: seyu
