name: Refresh README.md
run-name: ${{ github.event.workflow_run.head_commit.message }}
on:
  push:
    paths:
      - "백준/**"
jobs:
  refresh:
    runs-on: ubuntu-latest
    name: Refresh README.md
    steps:
      - uses: actions/checkout@v4
      - uses: seheon99/baekjoon-summary@8411607dcbf3f7c4a207d04251e3a38afc456204
        with:
          username: seyu
